### ISSUE TITLE
@scenario decorator is an overkill

### ISSUE THREAD

**Issue by spinus** [olegpidsadnyi/pytest-bdd#90]
Repeating full scenario phrase in feature file and then in ```@scenario``` decorator is a little cumbersome. As @bubenkoff said, that approach has few values over the implicit scenario detection. 
Some of them:
* assertion in scenario function (executed after scenario is run)
* scenarios can be parametrized and use fixtures
So removing @scenario decorator won't work as we want to have those features.
But maybe for simple feature files without a lot of requirements we can have a ```@scenarios('<feature_file>`)``` decorator which can generate all scenarios in specific feature file?

Then it could look like:
```
@scenarios("my.feature")
def _(fixture_for_all_scenarios_in_that_feature):
    pass
```
What do you think?

**Comment by bubenkoff** [comment]
i think that can be done, but with a warning that you're limiting yourself
and it can look like:

scenarios('my.feature')

so not a decorated variant, but cumulative

**Comment by spinus** [comment]
For my any solution which limits lines of code which I don't need is good :-)
+1 if it's possible to implement.

**Comment by bubenkoff** [comment]
this is not going to happen, discussed in #89
