### ISSUE TITLE
Simpler text matcher idea

### ISSUE THREAD

**Issue by spinus** [olegpidsadnyi/pytest-bdd#91]
Regex is powerful tool but sometimes this power is not needed.
Probably for most cases just simple parser could be used (idea stolen from behave framework) – https://pypi.python.org/pypi/parse could be used as supplement to regexes in case of matching scenarios.

In that case step definition could be like:
```
@Given("I have {number} items")
@Given("the temperature is {temperature:float}C")
```

**Comment by spinus** [comment]
Amazing! :-)

**Comment by tedlandis** [comment]
Thank you so much for adding non-re parsers. This removes the last concern we had to migrating from Behave to pytest-bdd.

**Comment by bubenkoff** [comment]
Looking forward  for the feedback!
We'll release new version soon

**Comment by bubenkoff** [comment]
2.6.0 is out, try it out
