### ISSUE TITLE
Not implemented scenarios are silently omitted.

### ISSUE THREAD

**Issue by spinus** [olegpidsadnyi/pytest-bdd#92]
When the test is not implemented they are not executed without a warning.
I can imagine scenario like:
1. I have a feature file with scenario "This is my scenario"
2. I have implemented scenario with:
```
@scenario("my.feature", "This is my scenario")
```
3. I forgot to add dot to a feature file and I'm adding now.
4. If I forgot to fix implementation the scenario is lost silently.

It would be nice to have a warning/error (pytest command line option?) to say that some tests are not implemented (or maybe even that some steps are never used?).

**Comment by bubenkoff** [comment]
i think this is a duplication of #90, please check

**Comment by spinus** [comment]
@bubenkoff seems like it can be duplication if somebody could use only ```scenarios```. But if in one file you use ```@scenario``` and not ```scenarios``` it's still the case I think.

**Comment by bubenkoff** [comment]
then i don't understand...
if you have this:

```python
@scenario('some.feature', 'Some Scenario')
def test_something():
    pass
```
it will fail immediately if you forgot something
May be you mean that it will not fail if the scenario in the feature file is empty by itself?

**Comment by spinus** [comment]
I'm not sure I'm talking about that in a good way. Let me use example.
``my_feature.feature``:
```
Feature: my feature
    Scenario: scenario1
        Given a
        When b
        Then c
```
and implementation:
``test_my_feature.py``:
```
# empty
```
When I run:
```
py.test
```
```
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
plugins: bdd
collected 0 items
```
No error about not implemented test.

**Comment by bubenkoff** [comment]
right, so you're about not bound scenarios problem
but in the issue description it was:

2. I have implemented scenario with:

@scenario("my.feature", "This is my scenario")

so i was confused.
The only realistic solution for me is the helper which we already have: `pytest-bdd generate-missing` command.
Also the `scenarios` mentioned in #90 will help a bit.
But it can not be solved completely: the entry point is the test, not the feature file, that's where it's `wrong`.
And it completely depends on which tests you've collected ATM, so you don't know if you've collected all tests or only subset of them (because pytest allows you to run only a certain folder or even just single test).
We could throw the warning, but it will look strange if you run single test while having big feature file

**Comment by spinus** [comment]
Yes, sorry for this. I was writting crap. The title of the issue is good, but first explanation pretty bad, I think I've lost focus when I was writting it :).

You're right about the test discovery, so I think it's a little problem here, that py.test is discovering test implementations here and not tests itself (as feature files). So it's easy to miss the test.
Probably for proper solution the test discrovery mechanism should discover feature files rather than python files.
Or...<crazy idea>tests can be put as module docs in py files</crazy idea> but this doesn't seem too good.

**Comment by bubenkoff** [comment]
the key point of pytest-bdd is to rely on pytest as mature framework, and not go too far from it.
Also imagine that there are no feature files at all, but instead it's just rst documentation, and you map your tests to the features written among the normal text.
It's what i actually plan to experiment with. And that's the additional illustration why it's GOOD that the entry point is the test (@scenario call) and not the feature file. Feature files are just text files, they are not the code.

**Comment by spinus** [comment]
1. I understand that, that's pretty good assumption.
2. I don't agree that this entrypoint is better, you can end up with tests which are not implemented. I would say implementation is detail, what is important in that case (for me) are the feature files (other stuff is just implementation details).
OK, I see your point and your way to implement stuff in pytest-bdd. I think this ticket can be closed than, right?

**Comment by bubenkoff** [comment]
well, if you have an implementation idea, how can it be solved, then don't
close it :)

On 8 January 2015 at 01:29, Tomasz Czyż <notifications@github.com> wrote:

>
>    1. I understand that, that's pretty good assumption.
>    2. I don't agree that this entrypoint is better, you can end up with
>    tests which are not implemented. I would say implementation is detail, what
>    is important in that case (for me) are the feature files (other stuff is
>    just implementation details). OK, I see your point and your way to
>    implement stuff in pytest-bdd. I think this ticket can be closed than,
>    right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/olegpidsadnyi/pytest-bdd/issues/92#issuecomment-69117672>
> .
>



-- 
Anatoly Bubenkov

**Comment by spinus** [comment]
I don't have now. If/When I have something useful I'll reopen or do MR.
