### ISSUE TITLE
pytest-bdd -> py.test || py.test-bdd?

### ISSUE THREAD

**Issue by spinus** [olegpidsadnyi/pytest-bdd#94]
I'm not sure but probably ```pytest``` command is somehow not used (legacy?). Pytest is using now ```py.test``` as entrypoint.
I think pytest-bdd could use plugins to integrate with py.test (like other plugins do) and then to run the test only ```py.test``` command would be needed. I only assume that ```output``` plugin has to be changed to what ```pytest-bdd``` is using right now, but I didn't look is it hard or not, just an idea.

If it would be not easy/not needed change, still maybe would be better to follow pytest and use something like ```py.test-bdd```?

**Comment by bubenkoff** [comment]
please close it then :)

**Comment by spinus** [comment]
Closed as invalid.
